# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
      - image: circleci/postgres:9.3
        environment:
          POSTGRES_DB: circle-test
          POSTGRES_USER: circleci
          POSTGRES_PASSWORD: circleci

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-python-dep-{{ checksum "requirements.txt" }}-{{ checksum "requirements-test.txt" }}
          - v1-python-dep-{{ checksum "requirements.txt" }}
          - v1-python-dep-

      - run:
          name: Install dependencies
          command: |
            virtualenv venv
            source venv/bin/activate
            pip install -r requirements.txt
            pip install -r requirements-test.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-python-dep-{{ checksum "requirements.txt" }}-{{ checksum "requirements-test.txt" }}

      - run:
          name: Set circle configuration
          command: |
            cp mirage/local_settings.circle.py mirage/local_settings.py

      - run:
          name: Migrate schema
          command: |
            source venv/bin/activate
            python manage.py migrate --noinput

      - run:
          name: Load fixtures
          command: |
            source venv/bin/activate
            ./load_fixtures.sh

      - run:
          name: Run tests
          command: |
            source venv/bin/activate
            python manage.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports
